spring.application.name=tapanaranja

spring.datasource.url=jdbc:mysql://localhost:3306/tapanaranjadb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=tapanaranjauser
spring.datasource.password=tapanaranjapassword

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

